### PR TITLE
Determine indent level from more modes

### PR DESCRIPTION
**Pull request by scop**
Pass CSS, GraphQL, HTML, Ruby, Svelte, and YAML mode indent setting to formatters that make use of it through `apheleia-formatters-js-indent`.

`prettier-markdown` and `prettier-scss` attempt to make use of this too, but `markdown-mode` and `scss-mode` don't have such a setting that I can tell. Left the uses in place for `indent-tabs-mode` support anyway.

BTW the `apheleia-formatters-js-indent` name and its description does not seem quite spot on, as it was already being (partially unsuccessfully) (ab?)used by some modes for which "JavaScript like"ness is a bit of a stretch :)

### CODE REVIEW

**Comment by scop** [comment]
Reworked against current main branch.

**Review by raxod502 — DISMISSED** [review]
:sparkles: Thank you! Sorry for merge conflicts.

**Comment by raxod502** [comment]
At least we got that pesky variable renamed though with the refactor!

**Review by raxod502 — APPROVED** [review]
:sparkles:

**Pull request merged**
