### PR TITLE
Add elm-format

### PR DESCRIPTION
**Pull request by elken**
Has the change to not report errors if it fails, I experiemented with using the below shell script which can be used instead if desired, though it wasn't 100% accurate.

``` shell
elm-format --yes "$1" || elm make "$1"
```

### CODE REVIEW

**Comment by elken** [comment]
Initial failure was #99

**Comment by raxod502** [comment]
Oh, sorry, I think I missed this. Let me take a look.

**Comment by elken** [comment]
Aware I can merge my own PRs now, personally unsure about doing that but if you're happy with this I can merge this in too :) @raxod502

**Comment by raxod502** [comment]
Sorry, should have gotten back to you much earlier about this. Yeah, please feel free.

**Pull request merged**
