### PR TITLE
Add support for dhall format

### PR DESCRIPTION
**Pull request by zzantares**
Adds a new formatter `dhall-format` used for [dhall](https://dhall-lang.org/).

### CODE REVIEW

**Comment by raxod502** [comment]
Hmmm, if this formatter can automatically delete code comments, I am not sure we should enable it by default...

**Comment by raxod502** [comment]
Is it supposed to be nondestructive and this is a bug? Or is it illegal to put comments in the place where there is one in your example?

**Comment by zzantares** [comment]
good catch, it seems this is a bug that has been reported upstream: https://github.com/dhall-lang/dhall-lang/issues/1275.

**Comment by raxod502** [comment]
OK, we can add support for the formatter, but not enable it by default, since it has this destructive behavior.

**Review by raxod502 — APPROVED** [review]
:sparkles:

**Pull request merged**
