### PR TITLE
Add support for tsx-ts-mode

### PR DESCRIPTION
**Pull request by danielpza**
Add support for .tsx files (aka react + typescript). `tsx-ts-mode` is one of the new major modes using tree-sitter in emacs 29

from emacs docs:

> tsx-ts-mode is an autoloaded, interactive and natively compiled
function defined in typescript-ts-mode.el.gz.
Signature
(tsx-ts-mode)
Documentation
Major mode for editing TypeScript.
In addition to any hooks its parent mode typescript-ts-base-mode might have run, this mode runs the hook tsx-ts-mode-hook, as the final or penultimate step during initialization.

### CODE REVIEW

**Review by raxod502 — COMMENTED** [review]
That makes sense to me. Can you move the alist entry so it follows alphabetical order, and update the changelog?

**Comment by danielpza** [comment]
> That makes sense to me. Can you move the alist entry so it follows alphabetical order, and update the changelog?

Updated!

**Comment by 404cn** [comment]
Please add (go-ts-mode . gofmt) too.

**Comment by danielpza** [comment]
> Please add (go-ts-mode . gofmt) too.

I cannot find the docs for `go-ts-mode`, is this one shipped in emacs-29?

**Review by raxod502 — APPROVED** [review]
:sparkles: LGTM with 8328a7202b14001d8967c2e954c2a911fee4bb0a, thanks!

**Pull request merged**
