### PR TITLE
Add support for SQL using `pgformatter`

### PR DESCRIPTION
**Pull request by abougouffa**
Add support for [`pgFormatter`](https://github.com/darold/pgFormatter) for `sql-mode`.

### CODE REVIEW

**Review by raxod502 — COMMENTED** [review]
Thanks! Mind adding it to the list in the changelog?

**Comment by abougouffa** [comment]
@raxod502 Thanks for the feedback, done!

**Comment by abougouffa** [comment]
I've resolved merge conflicts, should be ok to merge!

**Review by raxod502 — APPROVED** [review]
:sparkles:

**Pull request merged**
