### PR TITLE
Introduce apheleia-inhibit-functions

### LINKED ISSUE #134: Conditionally disable apheleia-mode locally
When working in shared code base, auto-formatting may lead to diff
noise disasters when there isn't a commonly agreed code formatting
convention (or worse: people don't even care).

With `apheleia-global-mode` enabled, I think we should add an option
to conditionally disable auto-formatting that is ran at every save,
but still not get in the way when we want to call
`apheleia-format-buffer` explicitly.

While still using `apheleia-global-mode`, adding a "dummy" formatter
to `apheleia-formatters` (like `#'ignore`), and set
`apheleia-formatter` to it `.dir-locals-2.el` may disable
auto-formatting, but it prevents us from `M-x apheleia-format-buffer`.

### PR DESCRIPTION
**Pull request by daanturo**
Fixes #134

(I accidentally force-pushed #135 from a shallow repo)

### CODE REVIEW

**Review by raxod502 — COMMENTED** [review]
Thanks, this will be very helpful. I think we can improve the design a little bit, though. `define-globalized-minor-mode` already has a feature that is intended to accomplish conditional enabling of a minor mode:

```
Signature
(define-globalized-minor-mode GLOBAL-MODE MODE TURN-ON [KEY VALUE]... BODY...)

Documentation
Make a global mode GLOBAL-MODE corresponding to buffer-local minor MODE.

TURN-ON is a function that will be called with no args in every buffer
and that should try to turn MODE on if applicable for that buffer.
```

So, if we make the `TURN-ON` function check `apheleia--not-inhibited` before calling `apheleia-mode`, I think it will accomplish the same, but more simply.

I don't mind changing that in your PR directly but I wanted to ask you your thoughts first.

**Comment by daanturo** [comment]
> So, if we make the `TURN-ON` function check `apheleia--not-inhibited` before calling `apheleia-mode`, I think it will accomplish the same, but more simply.

I think that's totally fine. For me, my condition is a bit slow to run so I originally want to defer checking until saving is triggered, but I can just modify it to add to `".dir-locals-2.el"` to evaluate just once anyway.

Cleaner code is superior, I'm in for `define-global-minor-mode`'s `TURN-ON`.

**Comment by raxod502** [comment]
Ok, cool. Yeah, I figured that if the user desired caching then they could simply implement that in their disable-function.

**Comment by raxod502** [comment]
How does this version look to you?

**Comment by daanturo** [comment]
We may need to dump those variables into the autoloads file, else `apheleia-global-mode` will:
```
Error caused by user's config or system: ~/.config/doom/config.el, (void-variable apheleia-inhibit)
```

**Comment by daanturo** [comment]
Ping @raxod502 , I added commit https://github.com/radian-software/apheleia/pull/138/commits/66f30de1795b95b2152e8d119ebbcd238f1daa84 .

**Comment by raxod502** [comment]
Yeah, sorry for the delay, that seems fine to me. Would be equally okay to autoload the variable individually.

Looks like CI is failing, let me see if I can fix that.

**Comment by raxod502** [comment]
Ah yes it's just checkdoc.

**Comment by raxod502** [comment]
Thanks!

**Pull request merged**
